apiVersion: apps/v1
kind: Deployment
metadata:
  name: postas-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postas-worker
  template:
    metadata:
      labels:
        app: postas-worker
    spec:
      containers:
      - name: worker
        image: msa-worker:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: postas-worker-service
  labels:
    app: postas-worker
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  selector:
    app: postas-worker
